version: 0.2
 
phases:
  install:
    runtime-versions:
      java: openjdk8
  
    commands:
      - apt-get install openjdk-8-jdk

  build:
    commands:
      - echo Build started on `date`
      - mvn test

  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
   
artifacts:
  type: 
  files:
    - target/sparkjava-hello-world-1.0.war
