version: 0.2
 
phases:
  install:
    runtime-versions:
      java: corretto11
  
    commands:
      - apt-get install -y maven
      - apt-get install -y unzip

  build:
    commands:
      - echo Build started on `date`
      - mvn test

  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - zip helloworld.zip ./target/sparkjava-hello-world-1.0.war

artifacts:
  type: 
  files:
    - target/sparkjava-hello-world-1.0.war
    - /appspec.yml
