#!/bin/bash
sudo apt-get update
sudo apt-get -y install default-jdk
sudo groupadd tomcat
sudo useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat
cd /tmp
wget https://www-us.apache.org/dist/tomcat/tomcat-9/v9.0.26/bin/apache-tomcat-9.0.26.tar.gz
sudo mkdir /opt/tomcat
cd /opt/tomcat
sudo tar xzvf /tmp/apache-tomcat-9.0.*tar.gz -C /opt/tomcat --strip-components=1
sudo chgrp -R tomcat /opt/tomcat
sudo chmod -R g+r conf
sudo chmod g+x conf
sudo chown -R tomcat webapps/ work/ temp/ logs/
cd /home/ubuntu
sudo wget https://raw.githubusercontent.com/Kodeedudey/aws-codepipeline-s3-codedeploy-linux/master/scripts/tomcat.service
sudo cp /home/ubuntu/tomcat.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo /opt/tomcat/bin/startup.sh run
sudo ufw allow 8080

